### ISSUE TITLE
crash on start, ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

### ISSUE THREAD

**Issue by fluid-decanter** [thedarkcolour/ThaumcraftAltarCull#1]
I like the idea of this mod, but it crashes when I try it. I've uploaded my MultiMC log [here](https://paste.ee/p/XoAI1).

It seems like perhaps there is a dependency not mentioned on the Modrinth page? Something to do with [this project](https://github.com/SpongePowered/Mixin)?

**Comment by thedarkcolour** [comment]
That's definitely possible, I made this mod in a hurry using the GTNH template and didn't really check if there was a dependency required.

Maybe try using this mod? [GTNH Mixins](https://www.curseforge.com/minecraft/mc-mods/gtnhmixins)

**Comment by fluid-decanter** [comment]
Thanks for the suggestion, but unfortunately, that does not seem to fix it. GTNH Mixins works fine with other mods, but does not fix the crash from this mod. MultiMC log of most recent attempt [here](https://paste.ee/p/iU9Jq).

**Comment by fluid-decanter** [comment]
Following up to say that UniMixins and GTNH Lib together seem to have solved the issue for me.
